import type { ParsedSkill } from '@repo/skills-kit'

/**
 * Server-side skills data utilities
 * 
 * Uses src/data/ for direct ES module imports (better for SSR/SSG):
 * - Bundled at build time (no runtime HTTP requests)
 * - Works in both server and client environments
 * - Type-safe imports
 * - No filesystem access needed
 * 
 * For client-side language-specific mappings, see:
 * - @/lib/skills.client.ts - Client-side utilities for public/data/
 * - @/lib/hooks/use-language-mapping.ts - React hook for language-aware mappings
 * 
 * The public/data/ directory contains language-specific search mappings
 * (search-mapping.{locale}.json) that can be fetched at runtime for
 * client-side language switching without full page reloads.
 */

// Import pre-built JSON data directly (generated by scripts/generate-build-data.ts)
// This works in both server and client environments (no fs module needed)
import skillsData from '@/data/skills.json'
import searchMappingData from '@/data/search-mapping.json'

export interface SkillWithStats extends ParsedSkill {
  installCount?: number
  trendingScore?: number
  createdAt?: string | Date
  updatedAt?: string | Date
}

interface SearchMapping {
  tags: Record<string, { count: number; skills: Array<string> }>
  categories: Record<string, { count: number; skills: Array<string> }>
  skills: Record<string, { name: string; description: string; category?: string; tags: Array<string> }>
}

// Type the imported JSON data
const skills = skillsData as Array<SkillWithStats>
const searchMapping = searchMappingData as SearchMapping

// Cache for skills with Date objects converted
let skillsCache: Array<SkillWithStats> | null = null

/**
 * Get all skills with metadata from pre-built JSON
 */
export function getAllSkills(): Array<SkillWithStats> {
  if (skillsCache) {
    return skillsCache
  }
  
  // Convert date strings to Date objects
  skillsCache = skills.map(skill => ({
    ...skill,
    createdAt: skill.createdAt ? new Date(skill.createdAt as string) : undefined,
    updatedAt: skill.updatedAt ? new Date(skill.updatedAt as string) : undefined,
  }))
  
  return skillsCache
}

/**
 * Get a single skill by name
 */
export function getSkillByName(name: string): SkillWithStats | null {
  const allSkills = getAllSkills()
  return allSkills.find(skill => skill.metadata.name === name) || null
}

/**
 * Get all unique categories from pre-built search mapping
 */
export function getCategories(): Array<string> {
  return Object.keys(searchMapping.categories).sort()
}

/**
 * Get all unique tags from pre-built search mapping
 */
export function getAllTags(): Array<string> {
  return Object.keys(searchMapping.tags).sort()
}
